### ISSUE TITLE
Hue V1

### ISSUE THREAD

**Issue by aladin2000** [CrisMon-01/RESTatHome#1]
Hi
Is these develpoppement able to interact with Philips Hue V1 ? 

If yes, does it include creation of groups and paring for new bulb ?

**Comment by CrisMon-01** [comment]
Hi, I think it could work with v1, but I can't test it, for the creation of group and pair new lamp, it's a great idea, I could work on it

Stay tuned

**Comment by aladin2000** [comment]
In the mean Time i bought GU10 E27 and plug
I used plugin from  official site
And everything worked
Except scene as far as my tests went Yesterday



1 févr. 2021 23:38:55 Cristian Monti <notifications@github.com>:

**Comment by CrisMon-01** [comment]
The scene is a little bit complicated to manage for my "front-end" skill right now (if someone know how to manage and make it pretty, I will appreciate).
I put it in the backlog and close the issue tomorrow

**Comment by CrisMon-01** [comment]
@aladin2000 
I made the function to create new group by selecting (already) paired bulb, I will try to make the new pair work, but I don't think you can without involving the bridge
